# Generated by Django 5.2.7 on 2025-10-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_data_predicted_value_alter_data_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField()),
                ('country_of_residence', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=100)),
                ('cc_num', models.CharField(max_length=20)),
                ('type_of_card', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('trans_num', models.CharField(max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_of_transaction', models.CharField(max_length=50)),
                ('entry_mode', models.CharField(max_length=50)),
                ('is_fraud', models.BooleanField(default=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('merchant_group', models.CharField(max_length=100)),
                ('country_of_transaction', models.CharField(max_length=100)),
                ('merch_lat', models.FloatField()),
                ('merch_long', models.FloatField()),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('time', models.TimeField()),
                ('trans_date_trans_time', models.DateTimeField()),
                ('unix_time', models.BigIntegerField()),
                ('shipping_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('city_pop', models.IntegerField()),
            ],
        ),
    ]
