# Generated by Django 5.2.7 on 2025-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
